name: mistral-function-calling
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.11
  - ipykernel
  - pip:
      - langchain
      - langchain-community
      - langchain-experimental
      - prodiapy
      - python-dotenv
      - openai
